name: CI

on:
  push:
    branches: [master, qa]
    paths:
      - 'src/**'
      - 'artifacts/**'
      - '.github/workflows/main.yaml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set-up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 18

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test project with Maven
        run: mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 18
      - run: mvn -B package --file pom.xml -DskipTests
      - run: mkdir staging && cp target/PizzaDronz-*.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: PizzaDronz
          path: staging